// Field schema — ported verbatim from source-2-form-storage.js lines 3–99.
// `col` = spreadsheet header (single source of truth for import/export/template).

import type { FieldDef, GroupDef, OfferData } from '@/lib/offers/types'

export const GROUPS: GroupDef[] = [
  { n: 'A', title: 'New Hire Details' },
  { n: 'B', title: 'Role, Employment & Compensation' },
  { n: 'C', title: 'Equipment & Swag' },
  { n: 'D', title: 'Encompass Setup' },
  { n: 'E', title: 'Compensation Plans & Polly Branch ID' },
  {
    n: 'F',
    title:
      'Custom Compensation Wording (optional — overrides the matching offer-letter line when filled)',
  },
]

export const FIELDS: FieldDef[] = [
  {
    id: 'employeeName',
    q: 1,
    g: 'A',
    label: 'Employee Name',
    col: 'Employee Name',
    type: 'text',
    req: true,
  },
  {
    id: 'preferredName',
    q: 2,
    g: 'A',
    label: 'Preferred Name',
    col: 'Preferred Name',
    type: 'text',
  },
  {
    id: 'email',
    q: 3,
    g: 'A',
    label: "New Hire's Email Address",
    col: 'Email',
    type: 'email',
    req: true,
  },
  {
    id: 'phone',
    q: 4,
    g: 'A',
    label: "New Hire's Phone Number",
    col: 'Phone',
    type: 'tel',
    req: true,
  },
  {
    id: 'fullAddress',
    q: 5,
    g: 'A',
    label: 'Full Address',
    col: 'Full Address',
    type: 'textarea',
    req: true,
  },
  {
    id: 'nmls',
    q: 6,
    g: 'A',
    label: 'NMLS Number',
    help: 'Sponsor for New Licensee, Blank if NA',
    col: 'NMLS Number',
    type: 'text',
  },
  {
    id: 'branchName',
    q: 7,
    g: 'A',
    label: 'Branch Name',
    col: 'Branch Name',
    type: 'text',
    req: true,
  },
  {
    id: 'branchManager',
    q: 8,
    g: 'A',
    label: 'Branch Manager',
    col: 'Branch Manager',
    type: 'text',
    req: true,
  },

  {
    id: 'workLocation',
    q: 9,
    g: 'B',
    label: 'Work Location',
    help: 'Where does the Employee Sit to do their work',
    col: 'Work Location',
    type: 'radio',
    req: true,
    options: [
      'Branch Office (required to report to the office each workday)',
      'Remote',
      'Flexible/Hybrid',
    ],
  },
  {
    id: 'position',
    q: 10,
    g: 'B',
    label: 'Position or Title',
    col: 'Position/Title',
    type: 'text',
    req: true,
  },
  {
    id: 'employmentType',
    q: 11,
    g: 'B',
    label: 'Employment Type',
    col: 'Employment Type',
    type: 'radio_other',
    req: true,
    options: [
      'Commissioned Sales',
      'Full Time - Operations',
      'Part Time - Operations',
      'Temporary',
    ],
  },
  {
    id: 'reportsTo',
    q: 12,
    g: 'B',
    label: 'Reports To',
    col: 'Reports To',
    type: 'text',
    req: true,
  },
  {
    id: 'ptoManager',
    q: 13,
    g: 'B',
    label: 'Time Clock or PTO Manager Name',
    help: 'If different than Reports To',
    col: 'PTO Manager',
    type: 'text',
  },
  {
    id: 'startDate',
    q: 14,
    g: 'B',
    label: 'Expected Start Date',
    help: 'Minimum one week unless approved for rapid onboarding. Background check must be complete prior to start.',
    col: 'Start Date',
    type: 'date',
    req: true,
  },
  {
    id: 'baseWage',
    q: 15,
    g: 'B',
    label: 'Base Wage',
    help: 'Enter ONE basis only — Hourly (with Hours/Week), Monthly, or Annual. The other figures are calculated automatically for the offer letter. Leave blank / $0 for commission-only.',
    type: 'base',
  },
  {
    id: 'baseHourly',
    q: 15,
    g: 'B',
    label: 'Base Wage — Hourly Rate',
    col: 'Base - Hourly Rate',
    type: 'text',
    hidden: true,
    help: 'Hourly rate (e.g. $20.00). If used, also enter Hours/Week.',
  },
  {
    id: 'baseHoursWeek',
    q: 15,
    g: 'B',
    label: 'Base Wage — Hours per Week',
    col: 'Base - Hours per Week',
    type: 'text',
    hidden: true,
    help: 'Scheduled hours per week; used to annualize hourly pay. Defaults to 40 if blank.',
  },
  {
    id: 'baseMonthly',
    q: 15,
    g: 'B',
    label: 'Base Wage — Monthly Amount',
    col: 'Base - Monthly Amount',
    type: 'text',
    hidden: true,
    help: 'Monthly base pay (e.g. $4,333).',
  },
  {
    id: 'baseAnnual',
    q: 15,
    g: 'B',
    label: 'Base Wage — Annual Amount',
    col: 'Base - Annual Amount',
    type: 'text',
    hidden: true,
    help: 'Annual base pay (e.g. $52,000).',
  },
  {
    id: 'bonusStructure',
    q: 16,
    g: 'B',
    label: 'Bonus Structure or Other Compensation',
    help: 'Blank if Not Applicable. Check all that apply and enter amounts.',
    type: 'bonus',
  },
  {
    id: 'bonusSignOnAmount',
    q: 16,
    g: 'B',
    label: 'Sign-On Bonus — Month 1 Amount',
    col: 'Bonus - Sign-On Amount',
    type: 'text',
    hidden: true,
    help: 'Sign-On bonus dollar amount (Month 1), e.g. $5,000.',
  },
  {
    id: 'bonusSignOnMonth2',
    q: 16,
    g: 'B',
    label: 'Sign-On Bonus — Month 2 Amount',
    col: 'Bonus - Sign-On Month 2 Amount',
    type: 'text',
    hidden: true,
    help: 'Sign-On amount paid in Month 2 (optional).',
  },
  {
    id: 'bonusSignOnMonth3',
    q: 16,
    g: 'B',
    label: 'Sign-On Bonus — Month 3 Amount',
    col: 'Bonus - Sign-On Month 3 Amount',
    type: 'text',
    hidden: true,
    help: 'Sign-On amount paid in Month 3 (optional).',
  },
  {
    id: 'bonusGuaranteeAmount',
    q: 16,
    g: 'B',
    label: 'Guarantee Amount per Month',
    col: 'Bonus - Guarantee Monthly Amount',
    type: 'text',
    hidden: true,
    help: 'Guaranteed dollar amount PER MONTH (e.g. $10,000). The offer letter converts this to bi-weekly automatically.',
  },
  {
    id: 'bonusGuaranteeMonths',
    q: 16,
    g: 'B',
    label: 'Guarantee Number of Months',
    col: 'Bonus - Guarantee # Months',
    type: 'text',
    hidden: true,
    help: 'How many months the guarantee runs (e.g. 3).',
  },
  {
    id: 'bonusPnlAmount',
    q: 16,
    g: 'B',
    label: 'P&L Credit 1 — Amount',
    col: 'Bonus - P&L Credit Amount',
    type: 'text',
    hidden: true,
    help: 'P&L credit dollar amount (slot 1).',
  },
  {
    id: 'bonusPnlMonth',
    q: 16,
    g: 'B',
    label: 'P&L Credit 1 — Month It Applies',
    col: 'Bonus - P&L Credit Month Applied',
    type: 'text',
    hidden: true,
    help: 'When P&L credit 1 applies, e.g. "September", "your second month", or a specific date.',
  },
  {
    id: 'bonusPnlAmount2',
    q: 16,
    g: 'B',
    label: 'P&L Credit 2 — Amount',
    col: 'Bonus - P&L Credit Amount 2',
    type: 'text',
    hidden: true,
    help: 'P&L credit dollar amount (slot 2, optional).',
  },
  {
    id: 'bonusPnlMonth2',
    q: 16,
    g: 'B',
    label: 'P&L Credit 2 — Month It Applies',
    col: 'Bonus - P&L Credit Month 2 Applied',
    type: 'text',
    hidden: true,
    help: 'When P&L credit 2 applies (optional).',
  },
  {
    id: 'bonusPnlAmount3',
    q: 16,
    g: 'B',
    label: 'P&L Credit 3 — Amount',
    col: 'Bonus - P&L Credit Amount 3',
    type: 'text',
    hidden: true,
    help: 'P&L credit dollar amount (slot 3, optional).',
  },
  {
    id: 'bonusPnlMonth3',
    q: 16,
    g: 'B',
    label: 'P&L Credit 3 — Month It Applies',
    col: 'Bonus - P&L Credit Month 3 Applied',
    type: 'text',
    hidden: true,
    help: 'When P&L credit 3 applies (optional).',
  },
  {
    id: 'bonusPnlNote',
    q: 16,
    g: 'B',
    label: "P&L Credit — How It's Earned (note)",
    col: 'Bonus - P&L Credit How Earned',
    type: 'textarea',
    hidden: true,
    help: 'Spell out how the P&L credit is earned and any conditions. Shown verbatim in the letter\'s "How It Works" column for the P&L Credit row.',
  },
  {
    id: 'bonusProductionAmount',
    q: 16,
    g: 'B',
    label: 'Production Bonus Amount',
    col: 'Bonus - Production Bonus Amount',
    type: 'text',
    hidden: true,
    help: 'Production bonus dollar amount (e.g. $100,000).',
  },
  {
    id: 'bonusProductionVolume',
    q: 16,
    g: 'B',
    label: 'Production Volume to Achieve',
    col: 'Bonus - Production Volume to Achieve',
    type: 'text',
    hidden: true,
    help: 'Production volume that must be reached (e.g. $2,000,000).',
  },
  {
    id: 'bonusProductionMaxMonths',
    q: 16,
    g: 'B',
    label: 'Production Max Months to Achieve',
    col: 'Bonus - Production Max Months to Achieve',
    type: 'text',
    hidden: true,
    help: 'Maximum months of onboarding to hit the volume (e.g. 5).',
  },
  {
    id: 'bonusPerFileDollar',
    q: 16,
    g: 'B',
    label: 'Per File Bonus Amount ($)',
    col: 'Bonus - Per File $ Amount',
    type: 'text',
    hidden: true,
    help: 'Per-file bonus dollar amount. Use $ and/or bps.',
  },
  {
    id: 'bonusPerFileBps',
    q: 16,
    g: 'B',
    label: 'Per File Bonus (bps)',
    col: 'Bonus - Per File bps',
    type: 'text',
    hidden: true,
    help: 'Per-file bonus in basis points. Use $ and/or bps.',
  },
  {
    id: 'bonusOverrideBps',
    q: 16,
    g: 'B',
    label: 'Override (bps)',
    col: 'Bonus - Override bps',
    type: 'text',
    hidden: true,
    help: 'Override in basis points (bps).',
  },
  {
    id: 'bonusAccelBps1',
    q: 16,
    g: 'B',
    label: 'Accelerated bps — Month 1',
    col: 'Bonus - Accelerated bps Month 1',
    type: 'text',
    hidden: true,
    help: 'Accelerated commission for Month 1, in basis points (e.g. 250).',
  },
  {
    id: 'bonusAccelBps2',
    q: 16,
    g: 'B',
    label: 'Accelerated bps — Month 2',
    col: 'Bonus - Accelerated bps Month 2',
    type: 'text',
    hidden: true,
    help: 'Accelerated commission for Month 2, in basis points (optional).',
  },
  {
    id: 'bonusAccelBps3',
    q: 16,
    g: 'B',
    label: 'Accelerated bps — Month 3',
    col: 'Bonus - Accelerated bps Month 3',
    type: 'text',
    hidden: true,
    help: 'Accelerated commission for Month 3, in basis points (optional).',
  },
  {
    id: 'bonusFunding',
    q: 17,
    g: 'B',
    label: 'Transition cost — who is responsible for funding it',
    col: 'Transition Cost',
    type: 'radio',
    req: true,
    options: ['Corporate', 'Branch', '50/50', 'N/A'],
  },
  {
    id: 'dualCapacity',
    q: 18,
    g: 'B',
    label:
      'Does the candidate work in a dual capacity as both a Loan Officer and a licensed Real Estate Agent (Realtor)?',
    col: 'Dual Capacity (LO+Realtor)',
    type: 'radio',
    inline: true,
    options: ['Yes', 'No'],
  },

  {
    id: 'equipment',
    q: 19,
    g: 'C',
    label: 'Equipment Package',
    help: 'Will be costed to the Branch unless specified otherwise in Special Instructions',
    col: 'Equipment Package',
    type: 'radio_other',
    req: true,
    otherLong: true,
    options: [
      'None',
      'Desktop 2 monitors',
      'Desktop 3 Monitors',
      'Laptop',
      'Laptop, docking station, 2 monitors',
    ],
  },
  {
    id: 'swagBox',
    q: 20,
    g: 'C',
    label: 'Which new hire Swag Box would you like sent out?',
    col: 'Swag Box',
    type: 'radio_other',
    otherLong: true,
    options: ['Operations', 'Loan Officer', 'Branch Manager', 'No New Hire Swag Box'],
  },
  {
    id: 'tshirt',
    q: 21,
    g: 'C',
    label: 'T-Shirt Size (Swag Box)',
    col: 'T-Shirt Size',
    type: 'text',
  },

  {
    id: 'pipelinePeople',
    q: 22,
    g: 'D',
    label: "List anyone who will need access to this person's pipeline in Encompass?",
    col: 'Pipeline Access - People',
    type: 'textarea',
  },
  {
    id: 'pipelineNeeded',
    q: 23,
    g: 'D',
    label: 'List any pipelines this hire will need access to:',
    col: 'Pipeline Access - Needed',
    type: 'textarea',
  },
  {
    id: 'encompassProfile',
    q: 24,
    g: 'D',
    label: 'Encompass Profile Type',
    col: 'Encompass Profile Type',
    type: 'radio',
    options: [
      'No selection',
      'Loan Officer',
      'Loan Officer Assistant',
      'Processor',
      'Branch Manager',
      'Closer',
      'Funder',
    ],
  },
  {
    id: 'assignedProcessor',
    q: 25,
    g: 'D',
    label: 'Who will be the assigned processor',
    help: 'List Processing Team, if there is not a specific processor',
    col: 'Assigned Processor',
    type: 'text',
  },
  {
    id: 'assignedLOA',
    q: 26,
    g: 'D',
    label: 'Who will be the assigned LOA',
    help: 'If None, N/A',
    col: 'Assigned LOA',
    type: 'text',
  },
  {
    id: 'loVolume',
    q: 27,
    g: 'D',
    label: 'LO projected volume and units',
    help: 'Mandatory for Loan Officers only',
    col: 'LO Projected Volume',
    type: 'textarea',
    tmplHide: true,
  },
  {
    id: 'mmiSnippet',
    q: 28,
    g: 'D',
    label: 'MMI snippet of the Loan Officer',
    help: 'Mandatory for Loan Officers only. Enter a link or note; attach the file separately.',
    col: 'MMI Snippet',
    type: 'text',
    tmplHide: true,
  },

  {
    id: 'compStandard',
    q: 29,
    g: 'E',
    label: 'Standard',
    help: 'Traditional FHA, Conventional & VA Loans, conforming high balance and Jumbo transactions. Enter in bps (e.g. 125 = 1.25%).',
    col: 'Comp - Standard %',
    type: 'text',
  },
  {
    id: 'compBranch',
    q: 30,
    g: 'E',
    label: 'Branch Marketing',
    help: 'Transactions derived from a branch office supplied marketing effort or branch office provided lead source. Enter in bps (e.g. 125 = 1.25%).',
    col: 'Comp - Branch Marketing %',
    type: 'text',
  },
  {
    id: 'compBuilder',
    q: 31,
    g: 'E',
    label: 'Builder Marketing',
    help: 'Transactions derived from a preferred builder relationship provided by branch. N/A if not applicable. Enter in bps (e.g. 125 = 1.25%).',
    col: 'Comp - Builder Marketing',
    type: 'text',
  },
  {
    id: 'compCorporate',
    q: 32,
    g: 'E',
    label: 'Corporate Marketing',
    help: 'Transactions derived from corporate supplied marketing efforts or corporate provided lead source. N/A if not offered. Enter in bps (e.g. 125 = 1.25%).',
    col: 'Comp - Corporate Marketing',
    type: 'text',
  },
  {
    id: 'compLeads',
    q: 33,
    g: 'E',
    label: 'Leads',
    help: 'Transactions derived from leads generation systems. N/A if not offered by the branch. Enter in bps (e.g. 125 = 1.25%).',
    col: 'Comp - Leads',
    type: 'text',
  },
  {
    id: 'compBrokered',
    q: 34,
    g: 'E',
    label: 'Brokered Loans',
    help: 'Only for Loan Officers that reasonably expect to do Brokered loans, otherwise N/A. Enter in bps (e.g. 125 = 1.25%).',
    col: 'Comp - Brokered Loans',
    type: 'text',
  },
  {
    id: 'compMinimum',
    q: 35,
    g: 'E',
    label: 'Minimum',
    help: 'Minimum compensation as a dollar amount on all loans, e.g. 3000 = $3,000 (N/A for no minimum).',
    col: 'Comp - Minimum',
    type: 'text',
  },
  {
    id: 'compMaximum',
    q: 35,
    g: 'E',
    label: 'Maximum',
    help: 'Max compensation as a dollar amount allowed on all loans, e.g. 10000 = $10,000 (N/A for no maximum).',
    col: 'Comp - Maximum',
    type: 'text',
  },
  {
    id: 'processingFee',
    q: 36,
    g: 'E',
    label: 'Processing Fee - AWM Funded',
    help: 'Defaults to $695 if Blank.',
    col: 'Processing Fee',
    type: 'text',
    tmplHide: true,
  },
  {
    id: 'underwritingFee',
    q: 37,
    g: 'E',
    label: 'Underwriting Fee - AWM Funded',
    help: 'Defaults to $895 if Blank.',
    col: 'Underwriting Fee',
    type: 'text',
    tmplHide: true,
  },
  {
    id: 'branchPricing',
    q: 38,
    g: 'E',
    label:
      "Is the Loan Officer's branch pricing being set up for a new branch or an existing branch?",
    col: 'Branch Pricing Setup',
    type: 'radio',
    req: true,
    options: ['New branch', 'Existing branch', 'The new hire is not licensed'],
  },
  {
    id: 'baseText',
    q: 39,
    g: 'F',
    label: 'Base Salary / Draw — custom wording',
    help: 'If filled, this exact text replaces the Base Salary line in the offer letter (e.g. a monthly draw). Leave blank to use the Hourly/Monthly/Annual fields.',
    col: 'Comp - Base/Draw Text',
    type: 'textarea',
  },
  {
    id: 'guaranteeText',
    q: 40,
    g: 'F',
    label: 'Guarantee — custom wording',
    help: 'If filled, replaces the Guaranteed Pay line verbatim (e.g. a VO or month-specific guarantee). Leave blank to use the Guarantee amount / # months fields.',
    col: 'Comp - Guarantee Text',
    type: 'textarea',
  },
  {
    id: 'perfileText',
    q: 41,
    g: 'F',
    label: 'Per-File / Support Override — custom wording',
    help: "If filled, replaces the Per-File line verbatim (e.g. an override on another producer's loans, with caps/conditions). Leave blank to use the Per-File $ / bps fields.",
    col: 'Comp - Per-File/Support Text',
    type: 'textarea',
  },
  {
    id: 'overrideText',
    q: 42,
    g: 'F',
    label: 'Override — custom wording',
    help: 'If filled, replaces the Override line verbatim (e.g. a tiered branch override with a per-loan cap). Leave blank to use the Override bps field.',
    col: 'Comp - Override Text',
    type: 'textarea',
  },
]

export const FIELD_BY_ID: Record<string, FieldDef> = Object.fromEntries(
  FIELDS.map((f): [string, FieldDef] => [f.id, f]),
)

/** Fields that map to a spreadsheet column. */
export const DATA_FIELDS: (FieldDef & { col: string })[] = FIELDS.filter(
  (f): f is FieldDef & { col: string } => Boolean(f.col),
)

export const HEADERS: string[] = DATA_FIELDS.map((f) => f.col)

export const META_COLS: string[] = ['Record ID', 'Status', 'Last Saved']

export const BONUS_GROUPS: Record<string, string[]> = {
  signon: ['bonusSignOnAmount', 'bonusSignOnMonth2', 'bonusSignOnMonth3'],
  guarantee: ['bonusGuaranteeAmount', 'bonusGuaranteeMonths'],
  pnl: [
    'bonusPnlAmount',
    'bonusPnlMonth',
    'bonusPnlAmount2',
    'bonusPnlMonth2',
    'bonusPnlAmount3',
    'bonusPnlMonth3',
    'bonusPnlNote',
  ],
  production: ['bonusProductionAmount', 'bonusProductionVolume', 'bonusProductionMaxMonths'],
  perfile: ['bonusPerFileDollar', 'bonusPerFileBps'],
  override: ['bonusOverrideBps'],
  accel: ['bonusAccelBps1', 'bonusAccelBps2', 'bonusAccelBps3'],
}

// S2 488 — inputs auto-formatted as dollar amounts.
export const DOLLAR_FIELD_IDS: string[] = [
  'baseMonthly',
  'baseAnnual',
  'bonusSignOnAmount',
  'bonusSignOnMonth2',
  'bonusSignOnMonth3',
  'bonusGuaranteeAmount',
  'bonusPnlAmount',
  'bonusPnlAmount2',
  'bonusPnlAmount3',
  'bonusProductionAmount',
  'bonusProductionVolume',
  'bonusPerFileDollar',
]

// S2 853–860 — sample row used by the import template workbook.
export const EXAMPLE: OfferData = {
  employeeName: 'Mickey Mouse',
  preferredName: 'Mickey',
  email: 'mickey.mouse@example.com',
  phone: '555.132.4567',
  fullAddress: '1313 Disneyland Dr, Anaheim, CA 92802',
  nmls: 'NA',
  branchName: 'Branch Disneyland',
  branchManager: 'Walt Disney',
  workLocation: 'Remote',
  position: 'Branch Sales Assistant',
  employmentType: 'Full Time - Operations',
  reportsTo: 'Walt Disney',
  ptoManager: '',
  startDate: '07/24/2026',
  baseHourly: '',
  baseHoursWeek: '',
  baseMonthly: '4,333',
  baseAnnual: '',
  bonusStructure: '',
  bonusFunding: 'N/A',
  dualCapacity: 'No',
  equipment: 'Laptop, docking station, 2 monitors',
  swagBox: 'Operations',
  tshirt: 'M',
  pipelinePeople: 'Self',
  pipelineNeeded: 'Branch Disneyland',
  encompassProfile: 'Loan Officer Assistant',
  assignedProcessor: 'NA',
  assignedLOA: 'NA',
  loVolume: '',
  mmiSnippet: '',
  compStandard: '',
  compBranch: '',
  compBuilder: '',
  compCorporate: '',
  compLeads: '',
  compBrokered: '',
  compMinimum: '',
  compMaximum: '',
  processingFee: '',
  underwritingFee: '',
  branchPricing: 'The new hire is not licensed',
}

// S2 346
export function uid(): string {
  return 'r' + Date.now().toString(36) + Math.random().toString(36).slice(2, 7)
}

// S2 637
export function nowIso(): string {
  return new Date().toISOString()
}

// S2 598–600
export function missingRequired(d: OfferData): FieldDef[] {
  return FIELDS.filter((f) => f.req && (!d[f.id] || String(d[f.id]).trim() === ''))
}
